language: python
python: 
    - "nightly"
    - "3.6-dev"
    - "miniconda-latest"
script:
    - python -c 'import sys; print(sys._mercurial)'
    - export PYTHONWARNINGS='ignore'; python -c 'print(1)'
